SELECT * FROM USER_TABLES ;

SELECT * FROM RENT;
SELECT * FROM CUSTOMER;
SELECT * FROM CAR;
SELECT * FROM KIND;
SELECT * FROM MILEAGE;

SELECT CTM_NO, CTM_NAME, TEL, ADDRESS, CTM_REMARK FROM CUSTOMER;

SELECT *
  FROM CUSTOMER
 WHERE CTM_NO IN(SELECT CTM_No
				 FROM RENT r LEFT OUTER JOIN CAR c ON r.CAR_NO = c.CAR_NO
				 WHERE c.IS_RENT = 0);
				 
