SELECT * FROM USER_TABLES ;

SELECT * FROM RENT;
SELECT * FROM CUSTOMER;
SELECT * FROM CAR;
SELECT * FROM KIND;
SELECT * FROM MILEAGE;

SELECT CTM_NO, CTM_NAME, TEL, ADDRESS, CTM_REMARK FROM CUSTOMER;

